# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
#  build:
#    runs-on: ubuntu-latest
#    needs: job1
#    steps:

#    - name: Checkout master
#      uses: actions/checkout@v2
#      with:
#          submodules: true

#    - name: Set up Node.js version
#      uses: actions/setup-node@v1
#      with:
#        node-version: '12.x'

#    - name: Install dependencies
#      run: npm ci

#    - name: Build
#      run: npm run build:ci
#    - name: Azure Login
#      uses: azure/login@v1
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}

#    - name: Azure deploy
#      uses: azure/CLI@v1
#      with:
#        inlinescript: az storage blob upload-batch --account-name frontwebstorage --account-key ${{ secrets.AZURE_ACCOUNT_KEY }} --source dist/digitary --destination 'digitary'
#    - name: Azure delete old js and css
#      uses: azure/CLI@v1
#      with:
#        inlineScript: |
#          date=`date --date="1 day ago" +%Y-%m-%dT%H:%MZ`
#          echo $date
#          az storage blob delete-batch --source digitary --account-name frontwebstorage --pattern "*.js" --if-unmodified-since $date --account-key ${{ secrets.AZURE_ACCOUNT_KEY }}
#          az storage blob delete-batch --source digitary --account-name frontwebstorage --pattern "*.css" --if-unmodified-since $date --account-key ${{ secrets.AZURE_ACCOUNT_KEY }}