on: [push]

env:
    NODE_VERSION: 14

name: ByggOgDeploy

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true
    - name: Run Az CLI script
      run: |
        az webapp list --query "[?state=='Running']"
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install
      run: npm install

    - name: npm build
      run: npm build
