# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - digitary

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build:ci

    - name: Archive build
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: deploy_dist
        path: dist/digitary/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: deploy_dist
    - name: Display structure of downloaded files
      run: ls -R
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: deploy_dist

#    - name: 'Deploy to Azure Web App'
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'digitary'
#        slot-name: 'production'
#        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1d18c585d1494affab73a946acfcadbf }}
#        package: dist/digitary